# Generated by Django 6.1.1 on 2026-09-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerleads', '0009_rename_user_created_idx_customerlea_user_id_ba7c43_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='customerlea_user_id_ba7c43_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='customerlea_action_4120ac_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='converted_from',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_person',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_lead',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
